#!/bin/sh

set -eu

for arch in 'i686' 'x86_64'; do
	make -j CC=${arch}-w64-mingw32-gcc CFLAGS="-Werror"
	dir=xpack-$(git describe --tags | tr -d v)-windows-${arch}-bin
	rm -rf $dir ${dir}.zip
	mkdir $dir
	cp libxpack.dll libxpack.lib libxpack.h *.exe $dir
	${arch}-w64-mingw32-strip ${dir}/libxpack.dll ${dir}/*.exe
	for file in COPYING; do
		sed < $file > ${dir}/${file}.txt -e 's/$/\r/g'
	done
	for file in README.md; do
		sed < $file > ${dir}/${file} -e 's/$/\r/g'
	done
	(cd ${dir} && zip -r ../${dir}.zip .)
done
